"""The bibliography — generated by walking `evidenced_by` edges (PROMPTS.md
D6), never hand-assembled or asked of a model. Every entry is a real,
already-persisted `WebEvidence` row: url, domain, tier, retrieved_at.
"""

from __future__ import annotations

from dataclasses import dataclass

from sqlmodel import select

from coursec.core.graph import Graph
from coursec.core.models import Concept, Edge, EdgeKind, LessonBlock, WebEvidence


@dataclass
class BibliographyEntry:
    url: str
    domain: str
    tier: str
    retrieved_at: str


def collect_bibliography(graph: Graph, concepts: list[Concept]) -> list[BibliographyEntry]:
    concept_ids = {c.id for c in concepts}
    lesson_block_ids = {
        b.id
        for b in graph.session.exec(
            select(LessonBlock).where(LessonBlock.concept_id.in_(concept_ids))
        )
    }
    source_ids = concept_ids | lesson_block_ids

    evidence_ids: set[str] = set()
    for edge in graph.session.exec(select(Edge).where(Edge.kind == EdgeKind.evidenced_by)):
        if edge.source_id in source_ids:
            evidence_ids.add(edge.target_id)

    entries = []
    for evidence_id in evidence_ids:
        evidence = graph.session.get(WebEvidence, evidence_id)
        if evidence is None:
            continue  # target was a SourceSpan, not a WebEvidence — not a bibliography entry
        entries.append(
            BibliographyEntry(
                url=evidence.url,
                domain=evidence.domain,
                tier=evidence.tier,
                retrieved_at=evidence.retrieved_at.isoformat(),
            )
        )
    entries.sort(key=lambda e: (e.domain, e.url))
    return entries
